flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- HTTP-4000.2.20
- HUnit-1.3.0.0
- MissingH-1.3.0.1
- MonadRandom-0.4
- QuickCheck-2.8.1
- StateVar-1.1.0.1
- abstract-deque-0.3
- abstract-par-0.3.3
- adjunctions-4.2.2
- aeson-0.10.0.0
- ansi-terminal-0.6.2.3
- async-2.0.2
- attoparsec-0.13.0.1
- base-orphans-0.4.4
- bifunctors-5
- bindings-DSL-1.0.23
- bindings-gsl-0.2.1
- cereal-0.4.1.1
- cmaes-0.2.2.1
- comonad-4.2.7.2
- conduit-1.2.5.1
- contravariant-1.3.3
- cpu-0.1.2
- distributive-0.4.4
- dlist-0.7.1.2
- either-4.4.1
- enclosed-exceptions-1.0.1.1
- erf-2.0.0.0
- exceptions-0.8.0.2
- extensible-exceptions-0.1.1.4
- free-4.12.1
- hashable-1.2.3.3
- hslogger-1.2.9
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-discover-2.2.0
- hspec-expectations-0.7.2
- kan-extensions-4.2.3
- lens-4.13
- lifted-base-0.2.3.6
- math-functions-0.1.5.2
- mmorph-1.0.4
- monad-control-1.0.0.4
- monad-par-0.3.4.7
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.3.2
- nats-1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.0.6
- parallel-io-0.3.3
- parsec-3.1.9
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.1
- quickcheck-io-0.1.2
- random-1.1
- reflection-2.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resourcet-1.1.6
- safe-0.3.9
- scientific-0.3.4.2
- semigroupoids-5.0.0.4
- semigroups-0.17.0.1
- setenv-0.1.1.3
- spoon-0.3.1
- statistics-0.13.2.3
- stm-2.4.4
- strict-0.3.2
- syb-0.6
- tagged-0.8.1
- text-1.2.1.3
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.1.0
- vector-th-unbox-0.2.1.3
- void-0.7.1
- yaml-0.8.15.1
resolver: ghc-7.10.2
